from typing import Any, Dict, List

import gradio as gr

from src.agent import run_agent
from src.audit import read_audit_records
from src.tool_registry import list_tools


def get_run_audit_records(
    call_ids: List[str],
) -> List[Dict[str, Any]]:
    """Return audit records belonging only to the current agent run."""

    if not call_ids:
        return []

    records = read_audit_records()

    matching_records = [
        record
        for record in records
        if record.call.call_id in call_ids
    ]

    return [
        record.model_dump(mode="json")
        for record in matching_records
    ]


def handle_request(
    user_request: str,
):
    """
    Run the agent and return user-facing execution details.
    """

    if not user_request or not user_request.strip():
        return (
            "Please enter a request.",
            [],
            [],
            [],
        )

    try:
        result = run_agent(
            user_request.strip()
        )

        tool_calls = [
            call.model_dump(mode="json")
            for call in result.tool_calls
        ]

        tool_results = [
            tool_result.model_dump(mode="json")
            for tool_result in result.tool_results
        ]

        call_ids = [
            call.call_id
            for call in result.tool_calls
        ]

        audit_records = get_run_audit_records(
            call_ids
        )

        return (
            result.final_answer,
            tool_calls,
            tool_results,
            audit_records,
        )

    except Exception:
        return (
            (
                "Agent execution failed. "
                "Please review the server logs for details."
            ),
            [],
            [],
            [],
        )


APP_DESCRIPTION = """
# Tool-Using Operations Agent

A controlled AI agent that selects and executes approved tools through a
validated execution layer.

The language model **proposes** tool calls. Application code decides what
tools exist, validates their arguments, executes them, captures failures,
and records an audit trail.

### Available tools

- **calculator** — deterministic arithmetic
- **search_inventory** — constrained SQLite inventory search
- **lookup_country** — structured World Bank country lookup

Try a single-tool request or a request that requires multiple tools.
"""


with gr.Blocks(
    title="Tool-Using Operations Agent",
) as demo:

    gr.Markdown(APP_DESCRIPTION)

    with gr.Row():
        request_box = gr.Textbox(
            label="Request",
            placeholder=(
                "Example: How many Electronics items are "
                "in inventory, and what is 347 multiplied "
                "by that number?"
            ),
            lines=3,
        )

    run_button = gr.Button(
        "Run Agent",
        variant="primary",
    )

    gr.Examples(
        examples=[
            [
                "What is 347 multiplied by 29?"
            ],
            [
                "What electronics are currently in inventory?"
            ],
            [
                "What is the capital, region, and income level of Japan?"
            ],
            [
                (
                    "How many Electronics items are in inventory, "
                    "and what is 347 multiplied by that number?"
                )
            ],
        ],
        inputs=request_box,
    )

    gr.Markdown("## Agent Response")

    final_answer = gr.Textbox(
        label="Final Answer",
        lines=5,
        interactive=False,
    )

    with gr.Row():
        tool_calls_output = gr.JSON(
            label="Tool Calls",
        )

        tool_results_output = gr.JSON(
            label="Tool Results",
        )

    gr.Markdown(
        "## Current Run Audit Trail\n"
        "Only tool executions generated by this request are shown."
    )

    audit_output = gr.JSON(
        label="Audit Records",
    )

    run_button.click(
        fn=handle_request,
        inputs=request_box,
        outputs=[
            final_answer,
            tool_calls_output,
            tool_results_output,
            audit_output,
        ],
    )


if __name__ == "__main__":
    demo.launch()